
from whisper_writer.special_phrases.special_phrase import SpecialPhrase


PUNCTUATION = [
    SpecialPhrase("exclamation mark", func=lambda:"!", space_before=False, space_after=True, end_of_sentence=True),
    SpecialPhrase("question mark", func=lambda: "?", space_before=False, space_after=True, end_of_sentence=True),
    SpecialPhrase("quote", func=lambda: "\"", space_before=True, space_after=False),
    SpecialPhrase("quotation mark", func=lambda: "\"", space_before=True, space_after=False),
    SpecialPhrase("hashtag", func=lambda: "#", space_before=True, space_after=False),
    SpecialPhrase("hash tag", func=lambda: "#", space_before=True, space_after=False),
    SpecialPhrase("dollar sign", func=lambda: "$", space_before=True, space_after=False),
    SpecialPhrase("percentage sign", func=lambda: "%", space_before=False, space_after=True),
    SpecialPhrase("ambersand", func=lambda: "&", space_before=True, space_after=True),
    SpecialPhrase("and symbol", func=lambda: "&", space_before=True, space_after=True),
    SpecialPhrase("single quote", func=lambda: "\'", space_before=True, space_after=False),
    SpecialPhrase("apostrophe", func=lambda: "\'", space_before=True, space_after=False),
    SpecialPhrase("open bracket", func=lambda: "(", space_before=True, space_after=False),
    SpecialPhrase("close bracket", func=lambda: ")", space_before=False, space_after=True),
    SpecialPhrase("asterisk", func=lambda: "*", space_before=True, space_after=False),
    SpecialPhrase("plus sign", func=lambda: "+", space_before=True, space_after=True),
    SpecialPhrase("comma", func=lambda: ",", space_before=False, space_after=True),
    SpecialPhrase("hyphen", func=lambda: "-", space_before=False, space_after=False),
    SpecialPhrase("dash", func=lambda: "-", space_before=True, space_after=True),
    SpecialPhrase("minus sign", func=lambda: "-", space_before=True, space_after=True),
    SpecialPhrase("full stop", func=lambda: ".", space_before=False, space_after=True, end_of_sentence=True),
    SpecialPhrase("forward slash", func=lambda: "/", space_before=False, space_after=False),
    SpecialPhrase("backslash", func=lambda: "\\", space_before=False, space_after=False),
    SpecialPhrase("back slash", func=lambda: "\\", space_before=False, space_after=False),
    SpecialPhrase("colon", func=lambda: ":", space_before=False, space_after=True),
    SpecialPhrase("semicolon", func=lambda: ";", space_before=False, space_after=True),
    SpecialPhrase("less than symbol", func=lambda: "<", space_before=True, space_after=True),
    SpecialPhrase("left arrow", func=lambda: "<", space_before=True, space_after=True),
    SpecialPhrase("open angled bracket", func=lambda: "<", space_before=True, space_after=False),
    SpecialPhrase("open angle bracket", func=lambda: "<", space_before=True, space_after=False),
    SpecialPhrase("greater than symbol", func=lambda: ">", space_before=True, space_after=True),
    SpecialPhrase("right arrow", func=lambda: ">", space_before=True, space_after=True),
    SpecialPhrase("close angled bracket", func=lambda: ">", space_before=False, space_after=True),
    SpecialPhrase("close angle bracket", func=lambda: ">", space_before=False, space_after=True),
    SpecialPhrase("equals sign", func=lambda: "=", space_before=True, space_after=True),
    SpecialPhrase("at sign", func=lambda: "@", space_before=False, space_after=False),
    SpecialPhrase("caret", func=lambda: "^", space_before=False, space_after=False),
    SpecialPhrase("up arrow", func=lambda: "^", space_before=False, space_after=False),
    SpecialPhrase("underscore", func=lambda: "_", space_before=False, space_after=False),
    SpecialPhrase("grave accent", func=lambda: "`", space_before=True, space_after=False),
    SpecialPhrase("open brace", func=lambda: "{", space_before=True, space_after=False),
    SpecialPhrase("open curly bracket", func=lambda: "{", space_before=True, space_after=False),
    SpecialPhrase("open curly brace", func=lambda: "{", space_before=True, space_after=False),
    SpecialPhrase("close brace", func=lambda: "}", space_before=False, space_after=True),
    SpecialPhrase("close curly bracket", func=lambda: "}", space_before=False, space_after=True),
    SpecialPhrase("close curly brace", func=lambda: "}", space_before=False, space_after=True),
    SpecialPhrase("vertical bar", func=lambda: "|", space_before=False, space_after=False),
    SpecialPhrase("or symbol", func=lambda: "|", space_before=False, space_after=False),
    SpecialPhrase("tilde", func=lambda: "~", space_before=True, space_after=False),
    SpecialPhrase("pound sign", func=lambda: "£", space_before=True, space_after=False),
    SpecialPhrase("euro sign", func=lambda: "€", space_before=True, space_after=False),
    SpecialPhrase("en dash", func=lambda: "–", space_before=True, space_after=True),
    SpecialPhrase("em dash", func=lambda: "—", space_before=False, space_after=False),
    SpecialPhrase("trademark sign", func=lambda: "™", space_before=False, space_after=True),
    SpecialPhrase("new line", func=lambda: "\n", space_before=False, space_after=False, end_of_sentence=True),
    SpecialPhrase("new paragraph", func=lambda:"\n\n", space_before=False, space_after=False, end_of_sentence=True),
]

PUNCTUATION_STRING: str = ''.join(set(sp.func() for sp in PUNCTUATION if sp.func() and sp.func() not in "'"))
